[package]
name = "server-database"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }

server-model = { workspace = true }
