[package]
name = "server-database"
version = "0.1.0"
edition = "2021"

[dependencies]
server-model = { workspace = true }

anyhow = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }